name: Listas de listas ejemplo

on:
  workflow_dispatch:
      inputs:
            lista_de_listas:
                    description: 'Lista de listas'
                            required: true
                                    default: '["a", "b"], ["c", "d"], ["e", "f"]'

                                    jobs:
                                      test:
                                          runs-on: ubuntu-latest
                                              steps:
                                                    - name: Mostrar las listas
                                                            run: |
                                                                      echo "Lista de listas: ${{ github.event.inputs.lista_de_listas }}"
                                                                      